### PR TITLE
 Recipe naming convention

### PR DESCRIPTION
**Pull request by danimtb**
Sorry for that horrible diff, it was due to getting rid of CRLF

### CODE REVIEW

**Comment by danimtb** [comment]
cc/ @uilianries

**Comment by solvingj** [comment]
looks good.  should we use `scm` feature too?

**Comment by danimtb** [comment]
It is still considered experimental, so better keep it as is

**Review by SSE4 — APPROVED** [review]

**Comment by uilianries** [comment]
@danimtb Thanks!

@solvingj SCM could be great when available as stable.

**Review by uilianries — COMMENTED** [review]
LGTM

**Comment by uilianries** [comment]
@danimtb there are no outdated packages:

abseil/20180600@bincrafters/stable

**Pull request merged**
